module.exports = {
  META: {
    START_GAME: 'START_GAME'
    , VIEW_SETTINGS: 'VIEW_SETTINGS'
    , UPDATE_SETTINGS: 'UPDATE_SETTINGS'
  }
  , MECHANICS: {
    GENERATE_FALLING_BLOCK: 'GENERATE_FALLING_BLOCK'
    , APPLY_GRAVITY: 'APPLY_GRAVITY'
    , SHIFT_FALLING_BLOCK: 'SHIFT_FALLING_BLOCK'
    , ROTATE_FALLING_BLOCK: 'ROTATE_FALLING_BLOCK'
    , SPEED_UP_FALLING_BLOCK: 'SPEED_UP_FALLING_BLOCK'
    , CHECK_GAME_STATE: 'CHECK_GAME_STATE'
    , TOGGLE_GRAVITY: 'TOGGLE_GRAVITY'
  }
  , BLOCK_TYPES: {
    LINE: 'LINE'
    , SQUARE: 'SQUARE'
    , LBLOCK: 'LBLOCK'
  }
  , DEFAULT_BLOCK: 'LINE'
  , KEYEVENTS: {
    LEFT_SHIFT: 37
    , RIGHT_SHIFT: 39
    , DOWN_SHIFT: 40
    , CLOCKWISE_ROTATION: 67
    , CCLOCKWISE_ROTATION: 88
    , TOGGLE_GRAVITY: 71
  }
};

